[package]
name = "bmcd"
version = "2.3.8"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75.0"

[dependencies]
actix = "0.13.5"
actix-files = "0.6.9"
actix-multipart = "0.7.2"
actix-web = { version = "4.12.1", features = ["openssl"] }
actix-ws = "0.3.0"
anyhow = "1.0.100"
async-compression = { version = "0.4.36", features = ["tokio", "gzip", "xz"] }
async-trait = "0.1.89"
base64 = "0.22.1"
board-info = { path = "../board_info/" }
build-time = "0.1.3"
bytes = "1.11.0"
chrono = "0.4.42"
circular-buffer = "1.2.0"
clap = { version = "4.5.53", features = ["cargo"] }
config = "0.15.8"
crc = "3.4.0"
evdev = { version = "0.13.2", features = ["tokio"] }
futures = "0.3.31"
gpiocdev = "0.8.0"
hex = "0.4.3"
humansize = "2.1.3"
humantime = "2.3.0"
if-addrs = "0.14.0"
inotify = "0.11.0"
nix = { version = "0.30.1", features = ["fs", "feature"] }
openssl = "0.10.75"
pwhash = "1.0.0"
rand = "0.9.2"
reqwest = { version = "0.13.1", features = ["stream"] }
rockfile = { version = "0.1.2" }
rockusb = { version = "0.3.0", features = ["libusb"] }
rusb = "0.9.4"
rustpiboot = "0.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
serde_with = "3.16.1"
sha2 = "0.10.9"
tar = "0.4.44"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = [
    "rt-multi-thread",
    "rt",
    "time",
    "macros",
    "io-util",
    "net",
] }
tokio-serial = { version = "5.4.5", features = ["rt", "codec"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = { version = "0.7.17", features = ["io-util"] }
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
wincode = { version = "0.2.5", features = ["derive"] }

[dev-dependencies]
tempdir = "0.3.7"

[features]
stubbed = []
vendored = ["openssl/vendored"]

